Update wat-ended.yml

diff --git a/.github/workflows/wat-ended.yml b/.github/workflows/wat-ended.yml
--- a/.github/workflows/wat-ended.yml
+++ b/.github/workflows/wat-ended.yml
@@ -12,6 +12,40 @@ jobs:
         env:
           GH_TOKEN: ${{ github.token }}   
         run: |
+
+          RESPONSE=$(gh api -X GET -H "Accept: application/vnd.github+json" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            -f check_name="WAT" \
+            /repos/${{ github.repository }}/commits/${{ github.event.client_payload.ref }}/check-runs)
+
+          CHECK_RUN_ID=$(echo "$RESPONSE" | jq -r '.check_runs[] | select(.status != "completed") | .id')
+
+          if [ -z "$CHECK_RUN_ID" ]; then
+          
+            echo "No check run with the name 'WAT' found."
+            PR_HEAD_SHA=$(echo "$RESPONSE" | jq -r '.check_runs[] | .pull_requests[0].head.sha')
+
+            if [ -z "$PR_HEAD_SHA" ]; then
+              echo "No valid PR head SHA found, cannot create a new check run."
+              exit 1
+            fi
+
+            RESPONSE=$(gh api -X POST -H "Accept: application/vnd.github+json" \
+              -H "X-GitHub-Api-Version: 2022-11-28" \
+              -f name='WAT' \
+              -f head_sha="$PR_HEAD_SHA" \
+              /repos/${{ github.repository }}/check-runs)
+              
+            PR_ID=$(echo "$RESPONSE" | jq -r '.pull_requests[0].number')
+            BRANCH_NAME=$(echo "$RESPONSE" | jq -r '.pull_requests[0].head.ref')
+            CHECK_RUN_ID=$(echo "$RESPONSE" | jq -r '.id')
+          
+            echo "Pull Request ID: $PR_ID"
+            echo "Branch Name: $BRANCH_NAME"
+          fi
+
+          echo "Check Run ID: $CHECK_RUN_ID"
+        
           gh api -X PATCH -H "Accept: application/vnd.github+json" \
             -H "X-GitHub-Api-Version: 2022-11-28" \
             -f 'conclusion=success' \
@@ -27,4 +61,4 @@ jobs:
           | [Get Offers](https://codeception.cloud/organizations/openclassrooms/environments/oc-52619#29465893) `Backend Issue`                                      | Product          | Preprod: Passed, Staging: Failed |
           | [Admin Can See Team Analytics Overview](https://codeception.cloud/organizations/openclassrooms/environments/oc-52619#29465893) `Frontend Issue`          | Analytics        | Preprod: Failed, Staging: Failed |
           ' \
-            /repos/${{ github.repository }}/check-runs/${{ github.event.client_payload.checkRunId }}  
+            /repos/${{ github.repository }}/check-runs/$CHECK_RUN_ID  
