Update wat-started.yml

diff --git a/.github/workflows/wat-started.yml b/.github/workflows/wat-started.yml
--- a/.github/workflows/wat-started.yml
+++ b/.github/workflows/wat-started.yml
@@ -25,10 +25,15 @@ jobs:
             echo "No check run with the name 'WAT' found."
             PR_HEAD_SHA=$(echo "$RESPONSE" | jq -r '.check_runs[] | select(.status != "completed") | .pull_requests[0].head.sha')
             
+            if [ -z "$PR_HEAD_SHA" ]; then
+              echo "No valid PR head SHA found, cannot create a new check run."
+              exit 1
+            fi
+
             RESPONSE=$(gh api -X POST -H "Accept: application/vnd.github+json" \
               -H "X-GitHub-Api-Version: 2022-11-28" \
               -f name='WAT' \
-              -f head_sha='$PR_HEAD_SHA' \
+              -f head_sha="$PR_HEAD_SHA" \
               /repos/${{ github.repository }}/check-runs)
               
             PR_ID=$(echo "$RESPONSE" | jq -r '.pull_requests[0].number')
